# Generated by Django 5.0 on 2023-12-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(max_length=10000)),
                ('rating', models.DecimalField(decimal_places=1, default=None, max_digits=3)),
                ('genre', models.CharField(max_length=15)),
            ],
        ),
    ]
