# Generated by Django 5.0 on 2023-12-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0003_alter_anime_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
