# Generated by Django 5.0 on 2023-12-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0004_anime_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
    ]
