# Generated by Django 5.0 on 2023-12-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0007_alter_anime_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(max_length=500),
        ),
    ]
