# Generated by Django 5.0 on 2023-12-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0008_alter_anime_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='img',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
